# Generated by Django 5.2.3 on 2025-07-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('date', models.DateTimeField()),
                ('location_city', models.CharField(choices=[('vinnytsia', 'Вінниця'), ('lutsk', 'Луцьк'), ('dnipro', 'Дніпро'), ('donetsk', 'Донецьк'), ('zhytomyr', 'Житомир'), ('uzhhorod', 'Ужгород'), ('zaporizhzhia', 'Запоріжжя'), ('ivano-frankivsk', 'Івано-Франківськ'), ('kyiv', 'Київ'), ('kropyvnytskyi', 'Кропивницький'), ('lviv', 'Львів'), ('mykolaiv', 'Миколаїв'), ('odesa', 'Одеса'), ('poltava', 'Полтава'), ('rivne', 'Рівне'), ('sumy', 'Суми'), ('ternopil', 'Тернопіль'), ('kharkiv', 'Харків'), ('kherson', 'Херсон'), ('khmelnytskyi', 'Хмельницький'), ('cherkasy', 'Черкаси'), ('chernivtsi', 'Чернівці'), ('chernihiv', 'Чернігів'), ('simferopol', 'Сімферополь'), ('yalta', 'Ялта'), ('kerch', 'Керч'), ('feodosiya', 'Феодосія'), ('yevpatoria', 'Євпаторія'), ('saki', 'Саки'), ('sevastopol', 'Севастополь')])),
                ('age_limit', models.BooleanField(default=False)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='joined_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
